#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-native-platform
Version  : 0.14
Release  : 4
URL      : https://github.com/adammurdoch/native-platform/archive/0.14.tar.gz
Source0  : https://github.com/adammurdoch/native-platform/archive/0.14.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18/native-platform-freebsd-amd64-libcpp-0.18.jar
Source4  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18/native-platform-freebsd-amd64-libcpp-0.18.pom
Source5  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.jar
Source6  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.pom
Source7  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18/native-platform-freebsd-amd64-libstdcpp-0.18.jar
Source8  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18/native-platform-freebsd-amd64-libstdcpp-0.18.pom
Source9  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.jar
Source10  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.pom
Source11  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18/native-platform-freebsd-i386-libcpp-0.18.jar
Source12  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18/native-platform-freebsd-i386-libcpp-0.18.pom
Source13  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.jar
Source14  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.pom
Source15  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18/native-platform-freebsd-i386-libstdcpp-0.18.jar
Source16  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18/native-platform-freebsd-i386-libstdcpp-0.18.pom
Source17  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18/native-platform-linux-aarch64-ncurses5-0.18.jar
Source18  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18/native-platform-linux-aarch64-ncurses5-0.18.pom
Source19  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-aarch64/0.18/native-platform-linux-aarch64-0.18.jar
Source20  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-aarch64/0.18/native-platform-linux-aarch64-0.18.pom
Source21  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.jar
Source22  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.pom
Source23  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18/native-platform-linux-amd64-ncurses5-0.18.jar
Source24  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18/native-platform-linux-amd64-ncurses5-0.18.pom
Source25  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.jar
Source26  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.pom
Source27  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18/native-platform-linux-amd64-ncurses6-0.18.jar
Source28  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18/native-platform-linux-amd64-ncurses6-0.18.pom
Source29  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.jar
Source30  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.pom
Source31  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64/0.18/native-platform-linux-amd64-0.18.jar
Source32  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64/0.18/native-platform-linux-amd64-0.18.pom
Source33  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.jar
Source34  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.pom
Source35  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18/native-platform-linux-i386-ncurses5-0.18.jar
Source36  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18/native-platform-linux-i386-ncurses5-0.18.pom
Source37  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.jar
Source38  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.pom
Source39  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18/native-platform-linux-i386-ncurses6-0.18.jar
Source40  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18/native-platform-linux-i386-ncurses6-0.18.pom
Source41  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.jar
Source42  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.pom
Source43  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386/0.18/native-platform-linux-i386-0.18.jar
Source44  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386/0.18/native-platform-linux-i386-0.18.pom
Source45  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.jar
Source46  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.pom
Source47  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-amd64/0.18/native-platform-osx-amd64-0.18.jar
Source48  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-amd64/0.18/native-platform-osx-amd64-0.18.pom
Source49  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.jar
Source50  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.pom
Source51  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64-min/0.18/native-platform-windows-amd64-min-0.18.jar
Source52  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64-min/0.18/native-platform-windows-amd64-min-0.18.pom
Source53  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.jar
Source54  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.pom
Source55  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64/0.18/native-platform-windows-amd64-0.18.jar
Source56  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64/0.18/native-platform-windows-amd64-0.18.pom
Source57  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386-min/0.18/native-platform-windows-i386-min-0.18.jar
Source58  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386-min/0.18/native-platform-windows-i386-min-0.18.pom
Source59  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.jar
Source60  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.pom
Source61  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386/0.18/native-platform-windows-i386-0.18.jar
Source62  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386/0.18/native-platform-windows-i386-0.18.pom
Source63  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.jar
Source64  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.pom
Source65  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform/0.18/native-platform-0.18.jar
Source66  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform/0.18/native-platform-0.18.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-native-platform-data = %{version}-%{release}
Requires: mvn-native-platform-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# Native-platform: Java bindings for native APIs
A collection of cross-platform Java APIs for various native APIs. Currently supports OS X, Linux, Windows and FreeBSD
on Intel architectures.

%package data
Summary: data components for the mvn-native-platform package.
Group: Data

%description data
data components for the mvn-native-platform package.


%package license
Summary: license components for the mvn-native-platform package.
Group: Default

%description license
license components for the mvn-native-platform package.


%prep
%setup -q -n native-platform-0.14

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-native-platform
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-native-platform/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18/native-platform-freebsd-amd64-libcpp-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18/native-platform-freebsd-amd64-libcpp-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18/native-platform-freebsd-amd64-libstdcpp-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18/native-platform-freebsd-amd64-libstdcpp-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18/native-platform-freebsd-i386-libcpp-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18/native-platform-freebsd-i386-libcpp-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18/native-platform-freebsd-i386-libstdcpp-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18/native-platform-freebsd-i386-libstdcpp-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18/native-platform-linux-aarch64-ncurses5-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18/native-platform-linux-aarch64-ncurses5-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64/0.18
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64/0.18/native-platform-linux-aarch64-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64/0.18
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64/0.18/native-platform-linux-aarch64-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18/native-platform-linux-amd64-ncurses5-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18/native-platform-linux-amd64-ncurses5-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18/native-platform-linux-amd64-ncurses6-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18/native-platform-linux-amd64-ncurses6-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.18
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.18/native-platform-linux-amd64-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.18
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.18/native-platform-linux-amd64-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18/native-platform-linux-i386-ncurses5-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18/native-platform-linux-i386-ncurses5-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18/native-platform-linux-i386-ncurses6-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18/native-platform-linux-i386-ncurses6-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.18
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.18/native-platform-linux-i386-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.18
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.18/native-platform-linux-i386-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.18
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.18/native-platform-osx-amd64-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.18
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.18/native-platform-osx-amd64-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64-min/0.18
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64-min/0.18/native-platform-windows-amd64-min-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64-min/0.18
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64-min/0.18/native-platform-windows-amd64-min-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.18
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.18/native-platform-windows-amd64-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.18
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.18/native-platform-windows-amd64-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386-min/0.18
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386-min/0.18/native-platform-windows-i386-min-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386-min/0.18
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386-min/0.18/native-platform-windows-i386-min-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.18
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.18/native-platform-windows-i386-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.18
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.18/native-platform-windows-i386-0.18.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.18
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.18/native-platform-0.18.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.18
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.18/native-platform-0.18.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18/native-platform-freebsd-amd64-libcpp-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.18/native-platform-freebsd-amd64-libcpp-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18/native-platform-freebsd-amd64-libstdcpp-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.18/native-platform-freebsd-amd64-libstdcpp-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18/native-platform-freebsd-i386-libcpp-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.18/native-platform-freebsd-i386-libcpp-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18/native-platform-freebsd-i386-libstdcpp-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.18/native-platform-freebsd-i386-libstdcpp-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18/native-platform-linux-aarch64-ncurses5-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64-ncurses5/0.18/native-platform-linux-aarch64-ncurses5-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64/0.18/native-platform-linux-aarch64-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-aarch64/0.18/native-platform-linux-aarch64-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18/native-platform-linux-amd64-ncurses5-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.18/native-platform-linux-amd64-ncurses5-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18/native-platform-linux-amd64-ncurses6-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.18/native-platform-linux-amd64-ncurses6-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.18/native-platform-linux-amd64-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.18/native-platform-linux-amd64-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18/native-platform-linux-i386-ncurses5-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.18/native-platform-linux-i386-ncurses5-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18/native-platform-linux-i386-ncurses6-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.18/native-platform-linux-i386-ncurses6-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.18/native-platform-linux-i386-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.18/native-platform-linux-i386-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.18/native-platform-osx-amd64-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.18/native-platform-osx-amd64-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64-min/0.18/native-platform-windows-amd64-min-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64-min/0.18/native-platform-windows-amd64-min-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.18/native-platform-windows-amd64-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.18/native-platform-windows-amd64-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386-min/0.18/native-platform-windows-i386-min-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386-min/0.18/native-platform-windows-i386-min-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.18/native-platform-windows-i386-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.18/native-platform-windows-i386-0.18.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.18/native-platform-0.18.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.18/native-platform-0.18.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-native-platform/LICENSE
