#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-native-platform
Version  : 0.14
Release  : 1
URL      : https://github.com/adammurdoch/native-platform/archive/0.14.tar.gz
Source0  : https://github.com/adammurdoch/native-platform/archive/0.14.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.jar
Source4  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.pom
Source5  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.jar
Source6  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.pom
Source7  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.jar
Source8  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.pom
Source9  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.jar
Source10  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.pom
Source11  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.jar
Source12  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.pom
Source13  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.jar
Source14  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.pom
Source15  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.jar
Source16  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.pom
Source17  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.jar
Source18  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.pom
Source19  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.jar
Source20  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.pom
Source21  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.jar
Source22  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.pom
Source23  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.jar
Source24  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.pom
Source25  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.jar
Source26  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.pom
Source27  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.jar
Source28  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.pom
Source29  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.jar
Source30  : https://repo.gradle.org/gradle/libs-releases/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.pom
Source31  : https://repo.gradle.org/gradle/libs-releases/org/fusesource/jansi/jansi/1.14/jansi-1.14.jar
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-native-platform-data = %{version}-%{release}
Requires: mvn-native-platform-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# Native-platform: Java bindings for native APIs
A collection of cross-platform Java APIs for various native APIs. Currently supports OS X, Linux, Windows and FreeBSD
on Intel architectures.

%package data
Summary: data components for the mvn-native-platform package.
Group: Data

%description data
data components for the mvn-native-platform package.


%package license
Summary: license components for the mvn-native-platform package.
Group: Default

%description license
license components for the mvn-native-platform package.


%prep
%setup -q -n native-platform-0.14

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-native-platform
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-native-platform/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.14
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.14/jansi-1.14.jar


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libcpp/0.14/native-platform-freebsd-amd64-libcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-amd64-libstdcpp/0.14/native-platform-freebsd-amd64-libstdcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libcpp/0.14/native-platform-freebsd-i386-libcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-freebsd-i386-libstdcpp/0.14/native-platform-freebsd-i386-libstdcpp-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses5/0.14/native-platform-linux-amd64-ncurses5-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64-ncurses6/0.14/native-platform-linux-amd64-ncurses6-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-amd64/0.14/native-platform-linux-amd64-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses5/0.14/native-platform-linux-i386-ncurses5-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386-ncurses6/0.14/native-platform-linux-i386-ncurses6-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-linux-i386/0.14/native-platform-linux-i386-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-amd64/0.14/native-platform-osx-amd64-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-osx-i386/0.14/native-platform-osx-i386-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-amd64/0.14/native-platform-windows-amd64-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform-windows-i386/0.14/native-platform-windows-i386-0.14.pom
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.jar
/usr/share/java/.m2/repository/net/rubygrapefruit/native-platform/0.14/native-platform-0.14.pom
/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.14/jansi-1.14.jar

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-native-platform/LICENSE
